name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
			-Dsonar.projectKey=react \
			-Dsonar.sources=. \
			-Dsonar.host.url=http://3.110.174.26:9000 \
			-Dsonar.token=sqp_d2ca04a1296de86d0daf27c8fa8a5dbc62445a33

